### PR TITLE
Querying across hierarchies with common base unit

### LINKED ISSUE #65: Allow /location/overlaps to work with new cache features
This issue is for looking into validation and any refactoring needed to allow the `/location/overlaps` endpoint to work with new cache features. New logic might be needed to determine intra-dataset 'crosswalks'.

Examples:
* ASGS 2016 SA1 <--> ASGS 2016 LGA
* ASGS 2016 ILOC <--> ASGS 2016 SA2

### PR DESCRIPTION
**Pull request by benjaminleighton**

### CODE REVIEW

**Comment by jyucsiro** [comment]
hi @benjaminleighton - could you include an example query? I've tried 
http://localhost:8080/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Flocalgovernmentarea%2F29399&areas=true&proportion=true&contains=false&within=false&output_type=http%3A%2F%2Flinked.data.gov.au%2Fdef%2Fasgs%23StatisticalAreaLevel1&crosswalk=true&count=1000&offset=0

But i get 
```
{'message': 'Internal Server Error', 'code': 500}
```

**Comment by jyucsiro** [comment]
Ah i'm trying now with updated URL to sparql endpoint. seems to be doing something now

**Comment by jyucsiro** [comment]
Test defined in https://github.com/CSIRO-enviro-informatics/loci-scripts/pull/22/files#diff-d90e98a974ceb2c4b916b576d91f1bc1 is passing now. 

Using this spot check example with an arbitrarily selected LGA (http://linked.data.gov.au/dataset/asgs2016/localgovernmentarea/12900) and an overlapping SA1 (http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/10302106217) - shown below

image

API results returns
```
{
  "uri": "http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/10302106217",
  "intersection_area": "9311120.62301000",
  "forwardPercentage": 0.1976829637,
  "featureArea": "1521018300.00000024",
  "reversePercentage": 0.6121636158
}
```

QGIS reports the area as `9311049.65402992`

So looks like the result is accurate to 4 significant figures. Good enough @benjaminleighton @ashleysommer @dr-shorthair ?

```

**Comment by benjaminleighton** [comment]
A possible test here would be to ask the API to get the meshblocks from both the SA1 and LGA then find the intersecting meshblocks, visualise those in QGIS and see whether they fully cover that overlapping area. Also check the area in QGIS is albers.

**Comment by jyucsiro** [comment]
Ok will extend tests to do a sum. Spot checking the smallest case
http://localhost:8080/api/v1/location/overlaps?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Flocalgovernmentarea%2F35790&areas=true&proportion=true&contains=false&within=false&output_type=http%3A%2F%2Flinked.data.gov.au%2Fdef%2Fasgs%23StatisticalAreaLevel1&crosswalk=true&count=1000&offset=0

Sum returned by API = 71,992,904
Feature area = 71,992,800

So 99.999% accurate... 

Will do on others

**Review by jyucsiro — APPROVED** [review]
Based on integration tests, results are within 99.9% accuracy for sum of intersecting areas in the result set vs feature area for a large proportion of LGAs.

**Review by ashleysommer — APPROVED** [review]

**Pull request merged**
